//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionDream.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FBID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Review { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
