//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionDream.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel;
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        [DisplayName("Upload File")]
        public string ProductImage { get; set; }
        public int ProductPrice { get; set; }
        public int ProductQuantity { get; set; }
        public string ProductDetails { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

    }
    
}
